ARG GO_IMAGE=golang:1.20-bullseye
##
## Build
##
FROM ${GO_IMAGE} AS build
    
WORKDIR /app

RUN apt update
RUN apt install wget
RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_arm64.deb
RUN apt install ./wkhtmltox_0.12.6.1-2.bullseye_arm64.deb -y
COPY go.mod ./
COPY go.sum ./
RUN go mod download
RUN mkdir /output

COPY ./cmd ./cmd
COPY ./internal ./internal
RUN go build -o /main ./cmd/wkhtmltopdf-app/
COPY ./config /config

# ##
# ## Deploy
# ##
FROM gcr.io/distroless/base-debian11 AS app

WORKDIR /

COPY --from=build ["/main", "/"]
COPY --from=build ["/config", "/config"]
COPY --from=build --chown=nonroot:nonroot ["/output", "/output"]
COPY --from=build ["/etc/fonts/fonts.conf", "/etc/fonts/fonts.conf"]
COPY --from=build ["/usr/local/bin/wkhtmltopdf", "/usr/local/bin/wkhtmltopdf"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libjpeg.so.62", "/usr/lib/aarch64-linux-gnu/libjpeg.so.62"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libpng16.so.16", "/usr/lib/aarch64-linux-gnu/libpng16.so.16"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libXrender.so.1", "/usr/lib/aarch64-linux-gnu/libXrender.so.1"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libfontconfig.so.1", "/usr/lib/aarch64-linux-gnu/libfontconfig.so.1"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libfreetype.so.6", "/usr/lib/aarch64-linux-gnu/libfreetype.so.6"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libX11.so.6", "/usr/lib/aarch64-linux-gnu/libX11.so.6"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libssl.so.1.1", "/usr/lib/aarch64-linux-gnu/libssl.so.1.1"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libcrypto.so.1.1", "/usr/lib/aarch64-linux-gnu/libcrypto.so.1.1"]
COPY --from=build ["/lib/aarch64-linux-gnu/libz.so.1", "/lib/aarch64-linux-gnu/libz.so.1"]
COPY --from=build ["/lib/aarch64-linux-gnu/libdl.so.2", "/lib/aarch64-linux-gnu/libdl.so.2"]
COPY --from=build ["/lib/aarch64-linux-gnu/libpthread.so.0", "/lib/aarch64-linux-gnu/libpthread.so.0"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libstdc++.so.6", "/usr/lib/aarch64-linux-gnu/libstdc++.so.6"]
COPY --from=build ["/lib/aarch64-linux-gnu/libm.so.6", "/lib/aarch64-linux-gnu/libm.so.6"]
COPY --from=build ["/lib/aarch64-linux-gnu/libgcc_s.so.1", "/lib/aarch64-linux-gnu/libgcc_s.so.1"]
COPY --from=build ["/lib/aarch64-linux-gnu/libc.so.6", "/lib/aarch64-linux-gnu/libc.so.6"]
COPY --from=build ["/lib/aarch64-linux-gnu/libexpat.so.1", "/lib/aarch64-linux-gnu/libexpat.so.1"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libuuid.so.1", "/usr/lib/aarch64-linux-gnu/libuuid.so.1"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libbrotlidec.so.1", "/usr/lib/aarch64-linux-gnu/libbrotlidec.so.1"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libxcb.so.1", "/usr/lib/aarch64-linux-gnu/libxcb.so.1"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libbrotlicommon.so.1", "/usr/lib/aarch64-linux-gnu/libbrotlicommon.so.1"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libXau.so.6", "/usr/lib/aarch64-linux-gnu/libXau.so.6"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libXdmcp.so.6", "/usr/lib/aarch64-linux-gnu/libXdmcp.so.6"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libbsd.so.0", "/usr/lib/aarch64-linux-gnu/libbsd.so.0"]
COPY --from=build ["/usr/lib/aarch64-linux-gnu/libmd.so.0", "/usr/lib/aarch64-linux-gnu/libmd.so.0"]
COPY --from=build ["/lib/ld-linux-aarch64.so.1", "/lib/ld-linux-aarch64.so.1"]

# EXPOSE 8080
# USER nonroot:nonroot

CMD ["/main"]