ARG GO_IMAGE=golang:1.20-bullseye
##
## Build
##
FROM ${GO_IMAGE} AS build
    
WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./cmd ./cmd
COPY ./internal ./internal
RUN go build -o /api ./cmd/api
COPY ./config ./config

##
## Deploy
##
FROM gcr.io/distroless/base-debian11 AS app

WORKDIR /

COPY --from=build ["/api", "/"]
COPY ["/config", "/config"]

EXPOSE 8080
USER nonroot:nonroot

CMD ["/api"]