aws:
  region: "ap-southeast-1"
  access-key-id: ""
  secret-access-key: ""

s3:
  bucket-name: "kaewsai-pdf"

sqs:
  input-queue-url: ""

app:
  output-path: "chromium-output"

mongodb:
  user: admin
  password: admin
  host: localhost
  port: 27017
  name: kaewsai_pdf
