ARG GO_IMAGE=golang:1.20-bullseye
FROM ${GO_IMAGE} AS build

RUN apt-get update && apt-get install -y graphviz
RUN go install github.com/kisielk/godepgraph@latest

WORKDIR /app

ENTRYPOINT [ "godepgraph" ]
